name: Publish K8S manifests changes
on:
    workflow_dispatch:
    push:
      paths:
      - k8s/**
jobs:
    publish-k8s:
        runs-on: ubuntu-latest
        steps: 
          - name: Create kubeconfig
            working-directory: ./k8s/
            run: |
              mkdir ${HOME}/.kube
              echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
              cat ${HOME}/.kube/config

          - name: Use context
            working-directory: ./k8s/
            run: kubectl config use-context aks-cluster01

          - name: Deploy to K8s
            working-directory: ./k8s/
            run: kubectl apply -f qrcode-k8s.yaml