name: Publish K8S manifests changes
on:
    push:
      paths:
      - k8s/**
jobs:
    publish-k8s:
        runs-on: ubuntu-latest
        steps: 
          - name: Create kubeconfig
            run: |
              mkdir ${HOME}/.kube
              echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
              cat ${HOME}/.kube/config
          - name: Use context
            run: kubectl config use-context aks-cluster01
          - name: Deploy to K8s
            working-directory: ./k8s/
            run: kubectl apply -f .