name: Build and Publish web-api image to Docker Hub
on:
    [workflow_dispatch]

jobs:
    build-api-image-for-testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build the docker image
              working-directory: ./api-fastapi/
              run: |
                docker build . --tag qrcode-api:test
                docker run -d -e AZURESTORAGECONNECTIONSTRINGQR=${{ secrets.AZURESTORAGECONNECTIONSTRINGQR }} -p 5000:80 qrcode-api:test
            - name: Setup Python v3.10 Environment
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: api-testing
              working-directory: ./tests/
              run: |

                python -m pip install --upgrade pip
                pip install -r requirements.txt
                python api_test.py
    

    build-and-publish-tested-image:
        runs-on: ubuntu-latest
        needs: [build-api-image-for-testing]
        steps:
          - uses: actions/checkout@v4
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          -
            name: Build and push
            uses: docker/build-push-action@v6
            with:
                context: "{{defaultContext}}:api-fastapi"
                push: true
                tags: |
                  eben98/qrcode-api:latest
                  eben98/qrcode-api:${{ github.sha }}
          - name: Create kubeconfig
            run: |
              mkdir ${HOME}/.kube
              echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
              cat ${HOME}/.kube/config
          - name: Use context
            run: kubectl config use-context aks-cluster01
          - name: Deploy to K8s
            run: kubectl apply -f k8s/

   

          
    



